#!/bin/sh

if [ -e /etc/config/minidlna ]; then
    /sbin/uci set minidlna.@minidlna[0].interface='br-lan eth0 wlan0'
    /sbin/uci commit minidlna
fi

[ -e /etc/config/netatalk ] || ln -s afpd /etc/config/netatalk 
[ -f /etc/config/samba -a ! -L /etc/config/samba ] && ln -s samba /etc/config/samba4
[ -f /etc/config/samba4 -a ! -L /etc/config/samba4 ] && ln -s samba4 /etc/config/samba

NO_ST_SERVICES="samba samba4 afpd vsftpd minidlna"

for service in $NO_ST_SERVICES; do
    if [ -e /etc/init.d/$service ]; then
        [ -e /etc/config/$service ] || touch /etc/config/$service
        SECTION=$service
        [ "$SECTION" == "samba4" ] && SECTION="samba"
        uci rename $service.@$SECTION[0]='config' >>/dev/null 2>&1
        uci set $service.config=$SECTION
        if /etc/init.d/$service enabled; then
            /sbin/uci set $service.config.enabled=1
        else
            /sbin/uci set $service.config.enabled=0
        fi
        /sbin/uci commit $service
    fi
done

exit 0
